# Generated by Django 5.2.8 on 2025-12-15 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_pedidoreposicion_fecha_vencimiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="producto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.producto"
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="stock_minimo",
            field=models.PositiveIntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="pedidoreposicion",
            name="cantidad",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Precio Costo",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Precio Venta",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?\\d{1,3}?[-.\\s]?\\(?\\d{1,4}\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
                        "Formato inválido.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cantidad",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rut",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,8}-[\\dkK]$", "Formato de RUT inválido."
                    )
                ],
            ),
        ),
    ]
