# Generated by Django 5.2.8 on 2025-12-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventario_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidoreposicion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Completado", "Completado"),
                    ("Entransito", "Entransito"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Pendiente",
                max_length=50,
            ),
        ),
    ]
