# Generated by Django 5.1.7 on 2025-12-16 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventario_stock_reservado_user_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,8}-[0-9kK]$', 'Formato de RUT inválido.')])),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{1,3}?[-.\\s]?\\(?\\d{1,4}\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$', 'Formato inválido.')])),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='empresa_direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='empresa_mombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='empresa_rut',
        ),
        migrations.RemoveField(
            model_name='user',
            name='empresa_telefono',
        ),
    ]
