# Generated by Django 5.2.8 on 2025-12-16 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_transaction_descripcion_alter_empresa_telefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_unitario",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Precio Costo",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Precio Venta",
            ),
        ),
    ]
