# Generated by Django 5.2.8 on 2025-12-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_producto_precio_unitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={
                    "invalid": "Por favor ingresa un correo electrónico válido.",
                    "unique": "Ya existe un proveedor con este correo.",
                },
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
